language: ruby
rvm:
  - 2.6.3

before_script:
 - chmod +x ./script/cibuild 

script: ./script/cibuild

branches:
  only:
  - master     
  - dev
addons:
  apt:
    packages:
    - libcurl4-openssl-dev

cache: bundler
