# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- dev

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseRubyVersion@0
    inputs:
      versionSpec: '>= 2.4'

  - script: gem install bundler
    displayName: 'Install Bundler'

  - script: 'bundle install' 
    displayName: 'Install Jekyll and Dependencies'

  - script: 'bundle exec jekyll build' 
    displayName: 'Build Jekyll Site'

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: '_site'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: _site'
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: '_site'