name: Html + CSS Beautifier
on: 
  push: 
    branches: 
    - master
    - dev
  pull_request:
    branches:
      - master
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Set up Yarn
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
      - name: Install Yarn Dependencies
        run: |
          yarn install
      - name: Beautify HTML + CSS
        run: |
          yarn prettier --config .prettierrc --write hub/
      - name: Commit And Push All Changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'Format All HTML + CSS Files'
          add: 'hub/ --force --all'
          push: true
          branch: dev
          pull: '--no-rebase'
